# Do: pin all runtime dependencies in this spec with PEP 440 version specifiers
name: agoro-field-boundary-detector-run-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python~=3.8.8
  - pip~=20.2
  - tqdm
  - pip:
      - torch
      - torchvision
      - pycocotools~=2.0.2
      - earthengine-api~=0.1.264
      - geopandas~=0.9.0
      - opencv-python~=4.5.1.48
